version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nms
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./vendor:/var/www/vendor
      - ./node_modules:/var/www/node_modules
    ports:
      - "8000:8000"
    networks:
      - nms

  web:
    image: nginx:alpine
    container_name: nms_web
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - nms

  db:
    image: mysql:8.0
    container_name: nms_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: nms
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nms
      MYSQL_PASSWORD: nms
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - nms

  node:
    image: node:18-alpine
    container_name: nms_node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run watch"

networks:
  nms:

volumes:
  dbdata:
